### ISSUE TITLE
Use a custom domain name

### ISSUE THREAD

**Issue by kerfootj** [kerfootj/wedding#1]
## Description
Update the site deployed to github pages at https://kerfootj.github.io/wedding/ to use a custom domain.

## Additional Info
- [Configuring a custom domain for GitHub Pages](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)

## Tasks 
- [ ] buy a domain
- [ ] add a CNAME record to the report with the domain
- [ ] add the domain to the pages section
- [ ] add the necessary config to the domain registry DNS settings
